-- ══════════════════════════════════════════════════════════
--  ECAP Database Schema  —  PostgreSQL
--  Run this file once to create all tables:
--      psql -U <user> -d ecap_db -f schema.sql
-- ══════════════════════════════════════════════════════════

-- ── Admin users ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS admin_users (
    id             SERIAL PRIMARY KEY,
    username       VARCHAR(50)  UNIQUE NOT NULL,
    password_hash  VARCHAR(255) NOT NULL,
    created_at     TIMESTAMPTZ  DEFAULT NOW()
);

-- ── Students ──────────────────────────────────────────────────
--  Populated by admin (Add Student) AND by student self-profile
CREATE TABLE IF NOT EXISTS students (
    id              SERIAL PRIMARY KEY,
    roll_number     VARCHAR(20)  UNIQUE NOT NULL,
    first_name      VARCHAR(100) NOT NULL,
    last_name       VARCHAR(100) NOT NULL,
    department      VARCHAR(20)  NOT NULL,
    date_of_birth   DATE,
    gender          VARCHAR(10),
    mobile          VARCHAR(15),
    email           VARCHAR(150),
    nationality     VARCHAR(80),
    religion        VARCHAR(80),
    aadhar_number   VARCHAR(12),
    city            VARCHAR(100),
    admission_year  INTEGER,
    current_year    VARCHAR(20),
    section         VARCHAR(5),
    parent_name     VARCHAR(150),
    parent_mobile   VARCHAR(15),
    address         TEXT,
    added_by        VARCHAR(20)  DEFAULT 'admin',  -- 'admin' | 'self'
    created_at      TIMESTAMPTZ  DEFAULT NOW(),
    updated_at      TIMESTAMPTZ  DEFAULT NOW()
);

-- ── Student qualifications ────────────────────────────────────
CREATE TABLE IF NOT EXISTS student_qualifications (
    id                   SERIAL PRIMARY KEY,
    student_id           INTEGER REFERENCES students(id) ON DELETE CASCADE,
    qualification        VARCHAR(50),
    from_year            INTEGER,
    to_year              INTEGER,
    certificate_type     VARCHAR(50),
    certificate_filename VARCHAR(255),
    created_at           TIMESTAMPTZ DEFAULT NOW()
);

-- ── Faculty ───────────────────────────────────────────────────
--  faculty_id  = T-000, T-001 … (auto-generated by admin)
CREATE TABLE IF NOT EXISTS faculty (
    id                   SERIAL PRIMARY KEY,
    faculty_id           VARCHAR(20)  UNIQUE NOT NULL,
    first_name           VARCHAR(100) NOT NULL,
    last_name            VARCHAR(100) NOT NULL,
    department           VARCHAR(20)  NOT NULL,
    role                 VARCHAR(60),
    date_of_birth        DATE,
    gender               VARCHAR(10),
    mobile               VARCHAR(15),
    email                VARCHAR(150),
    nationality          VARCHAR(80),
    religion             VARCHAR(80),
    aadhar_number        VARCHAR(12),
    city                 VARCHAR(100),
    highest_qualification VARCHAR(20),
    specialization       VARCHAR(200),
    experience_years     INTEGER,
    previous_college     VARCHAR(250),
    added_by             VARCHAR(20)  DEFAULT 'admin',   -- 'admin' | 'self'
    created_at           TIMESTAMPTZ  DEFAULT NOW(),
    updated_at           TIMESTAMPTZ  DEFAULT NOW()
);

-- ── Faculty qualifications ────────────────────────────────────
CREATE TABLE IF NOT EXISTS faculty_qualifications (
    id                   SERIAL PRIMARY KEY,
    faculty_id           INTEGER REFERENCES faculty(id) ON DELETE CASCADE,
    qualification        VARCHAR(50),
    from_year            INTEGER,
    to_year              INTEGER,
    certificate_type     VARCHAR(50),
    certificate_filename VARCHAR(255),
    created_at           TIMESTAMPTZ DEFAULT NOW()
);

-- ── Faculty experience ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS faculty_experience (
    id                   SERIAL PRIMARY KEY,
    faculty_id           INTEGER REFERENCES faculty(id) ON DELETE CASCADE,
    college              VARCHAR(250),
    designation          VARCHAR(100),
    from_year            INTEGER,
    to_year              INTEGER,
    certificate_filename VARCHAR(255),
    created_at           TIMESTAMPTZ DEFAULT NOW()
);

-- ── Fee payments ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS fee_payments (
    id               SERIAL PRIMARY KEY,
    roll_number      VARCHAR(20)   NOT NULL,
    student_name     VARCHAR(200),
    fee_type         VARCHAR(100),
    amount           DECIMAL(10,2),
    payment_method   VARCHAR(50),
    reference_number VARCHAR(100),
    status           VARCHAR(20)   DEFAULT 'submitted',
    created_at       TIMESTAMPTZ   DEFAULT NOW()
);

-- ── Marks ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS marks (
    id            SERIAL PRIMARY KEY,
    faculty_id    VARCHAR(20),
    department    VARCHAR(20),
    exam_type     VARCHAR(50),   -- Mid 1, Mid 2
    sub_type      VARCHAR(50),   -- Assignments, Quiz, Theory
    roll_number   VARCHAR(20),
    student_name  VARCHAR(200),
    marks_scored  INTEGER,
    created_at    TIMESTAMPTZ   DEFAULT NOW()
);

-- ── Attendance ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS attendance (
    id               SERIAL PRIMARY KEY,
    faculty_id       VARCHAR(20),
    department       VARCHAR(20),
    section          VARCHAR(10),
    roll_number      VARCHAR(30),
    student_name     VARCHAR(200),
    is_present       BOOLEAN       DEFAULT TRUE,
    attendance_date  DATE          DEFAULT CURRENT_DATE,
    created_at       TIMESTAMPTZ   DEFAULT NOW()
);

-- ── Useful indexes ────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_students_roll    ON students(roll_number);
CREATE INDEX IF NOT EXISTS idx_students_dept    ON students(department);
CREATE INDEX IF NOT EXISTS idx_faculty_fid      ON faculty(faculty_id);
CREATE INDEX IF NOT EXISTS idx_faculty_dept     ON faculty(department);
CREATE INDEX IF NOT EXISTS idx_marks_roll       ON marks(roll_number);
CREATE INDEX IF NOT EXISTS idx_attendance_roll  ON attendance(roll_number);
CREATE INDEX IF NOT EXISTS idx_attendance_date  ON attendance(attendance_date);
CREATE INDEX IF NOT EXISTS idx_fee_roll         ON fee_payments(roll_number);
